name: Test Pico CMS for Nextcloud

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request: {}

concurrency: build

jobs:
  test:
    name: Nextcloud ${{ matrix.NEXTCLOUD }} on PHP ${{ matrix.PHP_VERSION }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      APP_NAME: cms_pico
      NEXTCLOUD: ${{ matrix.NEXTCLOUD }}
      NEXTXLOUD_PGP_KEY: 28806A878AE423A28372792ED75899B9A724937A
      PHP_VERSION: ${{ matrix.PHP_VERSION }}

    strategy:
      matrix:
        include:
          - NEXTCLOUD: "releases/latest-21"
            PHP_VERSION: "7.3"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-21"
            PHP_VERSION: "7.4"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-21"
            PHP_VERSION: "8.0"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-22"
            PHP_VERSION: "7.3"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-22"
            PHP_VERSION: "7.4"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-22"
            PHP_VERSION: "8.0"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-23"
            PHP_VERSION: "7.3"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-23"
            PHP_VERSION: "7.4"
            NIGHTLY: false
          - NEXTCLOUD: "releases/latest-23"
            PHP_VERSION: "8.0"
            NIGHTLY: false
          - NEXTCLOUD: "daily/latest-master"
            PHP_VERSION: "7.3"
            NIGHTLY: true
          - NEXTCLOUD: "daily/latest-master"
            PHP_VERSION: "7.4"
            NIGHTLY: true
          - NEXTCLOUD: "daily/latest-master"
            PHP_VERSION: "8.0"
            NIGHTLY: true
          - NEXTCLOUD: "daily/latest-master"
            PHP_VERSION: "8.1"
            NIGHTLY: true
      fail-fast: false

    continue-on-error: ${{ matrix.NIGHTLY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer

      - name: Setup GnuPG
        run: |
          export GNUPGHOME="$(mktemp -d)"
          echo "GNUPGHOME=$GNUPGHOME" >> "$GITHUB_ENV"
          gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$NEXTXLOUD_PGP_KEY"

      - name: Download Nextcloud (branch '${{ env.NEXTCLOUD }}')
        run: |
          curl -L -o ~/nextcloud.tar.bz2 https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2
          curl -L -o ~/nextcloud.tar.bz2.asc https://download.nextcloud.com/server/$NEXTCLOUD.tar.bz2.asc

      - name: Verify Nextcloud's PGP signature
        run: |
          gpg --batch --verify ~/nextcloud.tar.bz2.asc ~/nextcloud.tar.bz2

      - name: Extract Nextcloud sources
        run: |
          tar xfjv ~/nextcloud.tar.bz2 -C ~

      - name: Get Nextcloud version
        run: |
          cd ~/nextcloud
          echo "NEXTCLOUD_VERSION=$(php -r 'require("version.php"); echo $OC_VersionString;')" | tee -a "$GITHUB_ENV"

      - name: Install Nextcloud ${{ env.NEXTCLOUD_VERSION }}
        run: |
          php ~/nextcloud/occ maintenance:install --database "sqlite" --admin-user "admin" --admin-pass "admin"

      - name: Build Pico CMS for Nextcloud (${{ env.APP_NAME }})
        run: |
          make build-dev version=latest

      - name: Extract ${{ env.APP_NAME }}'s sources
        run: |
          tar xfzv build/$APP_NAME-latest.tar.gz -C ~/nextcloud/apps

      - name: Remove Nextcloud version constraint from ${{ env.APP_NAME }}'s appinfo/info.xml
        if: ${{ matrix.NIGHTLY == true }}
        run: |
          sed -i -e '/<nextcloud/ s/max-version="[a-zA-Z0-9_.-]*"//g' ~/nextcloud/apps/cms_pico/appinfo/info.xml

      - name: Install ${{ env.APP_NAME }}
        run: |
          php ~/nextcloud/occ app:enable $APP_NAME

      - name: Run Nextcloud code checks on ${{ env.APP_NAME }}
        run: |
          echo + "php ~/nextcloud/occ app:check-code $APP_NAME -c private"
          php ~/nextcloud/occ app:check-code $APP_NAME -c private

          echo + "php ~/nextcloud/occ app:check-code $APP_NAME -c strong-comparison"
          php ~/nextcloud/occ app:check-code $APP_NAME -c strong-comparison

          echo + "php ~/nextcloud/occ app:check-code $APP_NAME -c deprecation"
          php ~/nextcloud/occ app:check-code $APP_NAME -c deprecation

      - name: Run PHPUnit tests of ${{ env.APP_NAME }}
        run: |
          php ~/nextcloud/apps/$APP_NAME/vendor/bin/phpunit --configuration ~/nextcloud/apps/$APP_NAME/tests/phpunit.xml
